/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")


}

dependencies {
//    implementation(platform(":versions")) //hier hätte ich vermutet, dass ich versions als plattform einbinden kann

    implementation(myLibs.slf4j.api) // das geht logischerweise
//    implementation(myLibs.slf4j.simple)  // das wird nicht aufgelöst
    implementation("org.slf4j:slf4j-simple:2.0.17")  // das löst die dependency resolution aus und ist daher nicht fix

    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
